USE finapp;

-- ── id 15 · Salário (income) ───────────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(15, 'SALARIO'),
(15, 'SALÁRIO'),
(15, 'PAGAMENTO'),
(15, 'FOLHA'),
(15, 'REMUNERACAO'),
(15, 'REMUNERAÇÃO'),
(15, 'VENCIMENTO'),
(15, 'PROVENTO'),
(15, 'HOLERITE');

-- ── id 16 · Freelance (income) ────────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(16, 'FREELANCE'),
(16, 'FREELA'),
(16, 'HONORARIO'),
(16, 'HONORÁRIO'),
(16, 'PROJETO'),
(16, 'SERVICO PRESTADO'),
(16, 'SERVIÇO PRESTADO'),
(16, 'CONSULTORIA'),
(16, 'PIX RECEBIDO');

-- ── id 17 · Alimentação (expense) ────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(17, 'IFOOD'),
(17, 'RAPPI'),
(17, 'UBER EATS'),
(17, 'UBEREATS'),
(17, 'MCDONALDS'),
(17, 'MC DONALDS'),
(17, 'BURGER KING'),
(17, 'BURGUER KING'),
(17, 'SUBWAY'),
(17, 'HABIB'),
(17, 'HABIBS'),
(17, 'BOB'),
(17, 'BOBS'),
(17, 'KFC'),
(17, 'PIZZA'),
(17, 'PIZZARIA'),
(17, 'PADARIA'),
(17, 'PANIFICADORA'),
(17, 'SUPERMERCADO'),
(17, 'MERCADO'),
(17, 'MERCEARIA'),
(17, 'HORTIFRUTI'),
(17, 'AÇOUGUE'),
(17, 'ACOUGUE'),
(17, 'CARREFOUR'),
(17, 'EXTRA'),
(17, 'PÃO DE AÇÚCAR'),
(17, 'PAO DE ACUCAR'),
(17, 'ATACADAO'),
(17, 'ATACADÃO'),
(17, 'ASSAI'),
(17, 'ASSAÍ'),
(17, 'WALMART'),
(17, 'SAMS CLUB'),
(17, 'COSTCO'),
(17, 'LANCHONETE'),
(17, 'RESTAURANTE'),
(17, 'CHURRASCARIA'),
(17, 'SUSHI'),
(17, 'JAPONESE'),
(17, 'JAPONÊS'),
(17, 'CAFE'),
(17, 'CAFETERIA'),
(17, 'STARBUCKS'),
(17, 'CONFEITARIA'),
(17, 'SORVETERIA'),
(17, 'ACAI'),
(17, 'AÇAÍ');

-- ── id 18 · Transporte (expense) ─────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(18, 'UBER'),
(18, '99'),
(18, '99POP'),
(18, 'CABIFY'),
(18, 'INDRIVER'),
(18, 'TÁXI'),
(18, 'TAXI'),
(18, 'ONIBUS'),
(18, 'ÔNIBUS'),
(18, 'METRO'),
(18, 'METRÔ'),
(18, 'BILHETE UNICO'),
(18, 'BILHETE ÚNICO'),
(18, 'BUSER'),
(18, 'COMBUSTIVEL'),
(18, 'COMBUSTÍVEL'),
(18, 'GASOLINA'),
(18, 'ETANOL'),
(18, 'DIESEL'),
(18, 'POSTO'),
(18, 'SHELL'),
(18, 'PETROBRAS'),
(18, 'IPIRANGA'),
(18, 'BR DISTRIBUIDORA'),
(18, 'RAIZEN'),
(18, 'RAÍZEN'),
(18, 'PEDÁGIO'),
(18, 'PEDAGIO'),
(18, 'AUTOPASS'),
(18, 'CONNECT CAR'),
(18, 'SEM PARAR'),
(18, 'VELOE'),
(18, 'ESTACIONAMENTO'),
(18, 'PARKING'),
(18, 'LOCADORA'),
(18, 'LOCALIZA'),
(18, 'MOVIDA'),
(18, 'UNIDAS'),
(18, 'HERTZ'),
(18, 'IPVA'),
(18, 'DPVAT'),
(18, 'SEGURO AUTO'),
(18, 'MANUTENCAO VEICULO'),
(18, 'MANUTENÇÃO VEÍCULO'),
(18, 'OFICINA'),
(18, 'MECANICO'),
(18, 'MECÂNICO'),
(18, 'BORRACHARIA'),
(18, 'LATARIA'),
(18, 'BICICLETARIA'),
(18, 'PATINETE'),
(18, 'YELLOW'),
(18, 'GROW');

-- ── id 19 · Moradia (expense) ────────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(19, 'ALUGUEL'),
(19, 'CONDOMINIO'),
(19, 'CONDOMÍNIO'),
(19, 'IPTU'),
(19, 'AGUA'),
(19, 'ÁGUA'),
(19, 'SABESP'),
(19, 'SANEAGO'),
(19, 'COPASA'),
(19, 'LUZ'),
(19, 'ENERGIA'),
(19, 'ELETRICIDADE'),
(19, 'ENEL'),
(19, 'CEMIG'),
(19, 'CPFL'),
(19, 'LIGHT'),
(19, 'ELEKTRO'),
(19, 'GAS'),
(19, 'GÁS'),
(19, 'COMGAS'),
(19, 'CÔMGAS'),
(19, 'INTERNET'),
(19, 'CLARO'),
(19, 'VIVO'),
(19, 'TIM'),
(19, 'OI'),
(19, 'NET'),
(19, 'BRISANET'),
(19, 'TELEFONE'),
(19, 'CELULAR'),
(19, 'MOVEL'),
(19, 'MOBILIARIO'),
(19, 'MOBILIÁRIO'),
(19, 'REFORMA'),
(19, 'MATERIAL CONSTRUCAO'),
(19, 'MATERIAL CONSTRUÇÃO'),
(19, 'LEROY MERLIN'),
(19, 'CASTORAMA'),
(19, 'C&C'),
(19, 'MADEIREIRA'),
(19, 'FERRAGEM'),
(19, 'ELETRICO'),
(19, 'ELÉTRICO'),
(19, 'ENCANADOR'),
(19, 'PINTOR'),
(19, 'FAXINA'),
(19, 'DIARISTA'),
(19, 'LIMPEZA'),
(19, 'PORTARIA');

-- ── id 20 · Lazer (expense) ──────────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(20, 'NETFLIX'),
(20, 'SPOTIFY'),
(20, 'AMAZON PRIME'),
(20, 'PRIME VIDEO'),
(20, 'DISNEY'),
(20, 'HBO'),
(20, 'APPLE TV'),
(20, 'PARAMOUNT'),
(20, 'GLOBOPLAY'),
(20, 'MUBI'),
(20, 'CRUNCHYROLL'),
(20, 'YOUTUBE PREMIUM'),
(20, 'DEEZER'),
(20, 'STEAM'),
(20, 'PLAYSTATION'),
(20, 'XBOX'),
(20, 'NINTENDO'),
(20, 'EPICGAMES'),
(20, 'NUUVEM'),
(20, 'CINEMA'),
(20, 'CINEMARK'),
(20, 'CINEPOLIS'),
(20, 'UCI'),
(20, 'INGRESSO'),
(20, 'SHOW'),
(20, 'CONCERTO'),
(20, 'TEATRO'),
(20, 'BALADA'),
(20, 'BOATE'),
(20, 'BAR'),
(20, 'CHOPERIA'),
(20, 'CERVEJA'),
(20, 'BEBIDA'),
(20, 'VINHO'),
(20, 'WHISKY'),
(20, 'LIVRARIA'),
(20, 'AMAZON LIVROS'),
(20, 'KINDLE'),
(20, 'VIAGEM'),
(20, 'HOTEL'),
(20, 'POUSADA'),
(20, 'AIRBNB'),
(20, 'BOOKING'),
(20, 'DECOLAR'),
(20, 'PASSAGEM'),
(20, 'LATAM'),
(20, 'GOL'),
(20, 'AZUL'),
(20, 'TAM'),
(20, 'PARQUE'),
(20, 'MUSEU'),
(20, 'ZOO'),
(20, 'AQUARIO'),
(20, 'AQUÁRIO'),
(20, 'CLUBE'),
(20, 'PISCINA');

-- ── id 21 · Saúde (expense) ──────────────────────────────────────────────
INSERT IGNORE INTO category_keywords (category_id, keyword) VALUES
(21, 'FARMACIA'),
(21, 'FARMÁCIA'),
(21, 'DROGARIA'),
(21, 'DROGA'),
(21, 'DROGASIL'),
(21, 'DROGARIA SAO PAULO'),
(21, 'ULTRAFARMA'),
(21, 'PAGUE MENOS'),
(21, 'PANVEL'),
(21, 'NISSEI'),
(21, 'MEDICAR'),
(21, 'REMEDIOS'),
(21, 'REMÉDIOS'),
(21, 'MEDICAMENTO'),
(21, 'CONSULTA'),
(21, 'MEDICO'),
(21, 'MÉDICO'),
(21, 'CLINICA'),
(21, 'CLÍNICA'),
(21, 'HOSPITAL'),
(21, 'UPA'),
(21, 'PRONTO SOCORRO'),
(21, 'LABORATORIO'),
(21, 'LABORATÓRIO'),
(21, 'EXAME'),
(21, 'DENTISTA'),
(21, 'ODONTO'),
(21, 'ORTODONTIA'),
(21, 'OTICA'),
(21, 'ÓTICA'),
(21, 'OCULISTA'),
(21, 'FISIOTERAPIA'),
(21, 'FISIOTERAPEUTA'),
(21, 'PSICOLOGIA'),
(21, 'PSICOLOGO'),
(21, 'PSICÓLOGO'),
(21, 'PSIQUIATRIA'),
(21, 'NUTRICIONISTA'),
(21, 'NUTRICAO'),
(21, 'NUTRIÇÃO'),
(21, 'ACADEMIA'),
(21, 'SMARTFIT'),
(21, 'SMART FIT'),
(21, 'BLUEFIT'),
(21, 'BODYTECH'),
(21, 'CROSSFIT'),
(21, 'PILATES'),
(21, 'YOGA'),
(21, 'PERSONAL'),
(21, 'PLANO DE SAUDE'),
(21, 'PLANO DE SAÚDE'),
(21, 'UNIMED'),
(21, 'AMIL'),
(21, 'SULAMERICA'),
(21, 'SUL AMERICA'),
(21, 'BRADESCO SAUDE'),
(21, 'BRADESCO SAÚDE'),
(21, 'HAPVIDA'),
(21, 'NOTREDAME'),
(21, 'NOTRE DAME'),
(21, 'PREVENT SENIOR'),
(21, 'GOLDEN CROSS');
